name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - run: pip install wget
    - name: Fetch
      run: wget -O zrok.tar.gz https://github.com/openziti/zrok/releases/download/v0.4.36/zrok_0.4.36_windows_amd64.tar.gz
    - name: Make Temp Path
      run: New-Item -Path "$env:TEMP\zrok" -ItemType Directory -ErrorAction Stop
    - name: Extract
      run: tar -xf .\zrok.tar.gz -C "$env:TEMP\zrok"
    - name: Set Path
      run: |
        $source = Join-Path -Path $env:TEMP -ChildPath "zrok\zrok.exe"
        $destination = Join-Path -Path $env:USERPROFILE -ChildPath "bin\zrok.exe"
        New-Item -Path $destination -ItemType Directory -ErrorAction SilentlyContinue
        Copy-Item -Path $source -Destination $destination
        $env:path += ";"+$destination
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Windows@10" -Force)
    - name: Modify Registry Settings
      run: |
        reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System" /v SystemBiosVersion /t REG_DWORD /d 1 /f
        reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System" /v SystemBiosDate /t REG_DWORD /d 1 /f
    - name: Create Tunnel
      run: C:\Users\runneradmin\bin\zrok.exe version
      

    
